<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Audit Log Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
        }
        h1 {
            font-size: 16px;
            text-align: center;
            margin-bottom: 10px;
        }
        .header-info {
            margin-bottom: 15px;
            font-size: 9px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th {
            background-color: #4F46E5;
            color: white;
            padding: 6px;
            text-align: left;
            font-size: 9px;
            border: 1px solid #ddd;
        }
        td {
            padding: 5px;
            border: 1px solid #ddd;
            font-size: 8px;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 8px;
            font-weight: bold;
        }
        .badge-create { background-color: #10B981; color: white; }
        .badge-update { background-color: #F59E0B; color: white; }
        .badge-delete { background-color: #EF4444; color: white; }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #666;
        }
        .data-preview {
            max-height: 50px;
            overflow: hidden;
            font-family: monospace;
            font-size: 7px;
        }
    </style>
</head>
<body>
    <h1>LAPORAN AUDIT LOG SISTEM</h1>
    
    <div class="header-info">
        <strong>Mini Market Jayusman</strong><br>
        Total Records: {{ $totalLogs }}<br>
        Generated: {{ now()->format('d/m/Y H:i:s') }}
        @if(auth()->user())
        <br>Generated by: {{ auth()->user()->name }}
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th width="12%">Waktu</th>
                <th width="12%">User</th>
                <th width="8%">Aksi</th>
                <th width="12%">Model</th>
                <th width="10%">IP Address</th>
                <th width="23%">Data Perubahan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($auditLogs as $log)
            <tr>
                <td>{{ $log->created_at->format('d/m/Y H:i') }}</td>
                <td>{{ $log->user->name ?? 'System' }}</td>
                <td>
                    @if($log->action == 'create')
                        <span class="badge badge-create">CREATE</span>
                    @elseif($log->action == 'update')
                        <span class="badge badge-update">UPDATE</span>
                    @elseif($log->action == 'delete')
                        <span class="badge badge-delete">DELETE</span>
                    @endif
                </td>
                <td>{{ class_basename($log->model_type) }} #{{ $log->model_id }}</td>
                <td>{{ $log->ip_address ?? '-' }}</td>
                <td class="data-preview">
                    @if($log->action == 'create' && $log->new_data)
                        @foreach(array_slice($log->new_data, 0, 3) as $key => $value)
                            <div><strong>{{ $key }}:</strong> {{ is_string($value) ? Str::limit($value, 30) : $value }}</div>
                        @endforeach
                    @elseif($log->action == 'update')
                        @php
                            $changes = [];
                            if($log->old_data && $log->new_data) {
                                foreach($log->old_data as $key => $oldVal) {
                                    if(isset($log->new_data[$key]) && $log->new_data[$key] != $oldVal) {
                                        $changes[$key] = $oldVal . ' → ' . $log->new_data[$key];
                                    }
                                }
                            }
                        @endphp
                        @foreach(array_slice($changes, 0, 2) as $key => $change)
                            <div><strong>{{ $key }}:</strong> {{ Str::limit($change, 40) }}</div>
                        @endforeach
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center; padding: 20px;">
                    Tidak ada data audit log untuk periode ini
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Dokumen ini dibuat secara otomatis oleh sistem. Audit Log ini bersifat rahasia dan hanya untuk internal.</p>
        <p>&copy; {{ date('Y') }} Mini Market Jayusman - All Rights Reserved</p>
    </div>
</body>
</html>